//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace attendance.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class schedule_info
    {
        [DisplayName("Schedule ID")]
        public int schedule_id { get; set; }
        [DisplayName("Schedule Name")]
        public string Schedule_name { get; set; }
        [DisplayName("Start Time")]
        public System.DateTime start_time { get; set; }
        [DisplayName("End Time")]
        public System.DateTime end_time { get; set; }
        [DisplayName("Start Before")]
        public double start_bf { get; set; }
        [DisplayName("Start After")]
        public Nullable<double> start_af { get; set; }
        [DisplayName("End Before")]
        public Nullable<double> end_bf { get; set; }
        [DisplayName("End After")]
        public Nullable<double> end_af { get; set; }
    }
}
